#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Trying to build now... 🔨'

npm run build-lib ||
(
    echo '👷 The build has failed: View the errors above to see why. 👷'
    false;
)


echo '✅ The code has been succcessfully pushed. ✅'
